### ISSUE TITLE
Wrong use of rdfs:domain

### ISSUE THREAD

**Issue by clange** [LaurenzNeumann/PHTMetadata#1]
Hi @LaurenzNeumann, Oya Beyan made me aware of your project. Great to see such a comprehensive ontology!

Here and in other places, there is, however, something wrong:

https://github.com/LaurenzNeumann/PHTMetadata/blob/7a2241755e7692d267ef9af8b79b027480cfa6cc/schema.ttl#L143-L145

Mentioning multiple classes as objects for `rdfs:domain` or `rdfs:range` does not define the range as the union of these classes (which is what you probably intended), but the _intersection_.

For the union, there are three recommended approaches:
* the strict, "heavyweight" one is to go from RDFS to OWL and use `owl:unionOf`.
* if you want to keep the ontology lightweight and stay within RDFS, you could define a common superclass _S_ of the various classes whose union you would like to use and refer to _S_ in the respective domains/ranges.
* if you would rather like to _document_ that certain classes _should_ be used with certain properties, you can use `schema:domainIncludes` and `schema:rangeIncludes`, which, however, do not have any formal semantics.

**Comment by LaurenzNeumann** [comment]
Hi @clange ! 
Thank you very much for bringing that to my notice! 
Since the current plan is to keep the ontology lightweight, I did choose the second one of your recommendations.
